apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJZVzVrY21WNUxYWXRkSE5oY21WMk9tZG9jRjh3VUdoeFdVMWljRlZGVmxNMWFFTlZOamhLWVZKRWIwZzBZbkJ5Tms0d1RHaDFZV0U9IgogICAgfQogIH0KfQoK
type: kubernetes.io/dockerconfigjson
